all:	
	g++ kruskal.cpp -lm -o kruskal.out
	g++ logestCommonSubsequence.cpp -lm -o logestCommonSubsequence.out
	g++ prim.cpp -lm -o prim.out

compile:
	g++ kruskal.cpp -lm -o kruskal.out
	g++ logestCommonSubsequence.cpp -lm -o logestCommonSubsequence.out
	g++	prim.cpp -lm -o prim.out	
	
clean:
	rm -rf prim.out logestCommonSubsequence.out kruskal.out