all:	
	g++ chaudhari_pa2_stra.cpp -lm -o strassen
	g++ chaudhari_pa2_tro.cpp -lm -o tromino
	gcc	chaudhari_pa2_floyd.c -lm -o floyd

compile:
	g++ chaudhari_pa2_stra.cpp -lm -o strassen
	g++ chaudhari_pa2_tro.cpp -lm -o tromino
	gcc	chaudhari_pa2_floyd.c -lm -o floyd

run_stra:
	./strassen

run_tro:
	./tromino

clean:
	rm -rf strassen tromino floyd