all:	
	g++ bruteforce_knapsack.cpp -lm -o bruteforce_knapsack.out
	g++ backtrack_knapsack.cpp -lm -o backtrack_knapsack.out
	

compile:
	g++ bruteforce_knapsack.cpp -lm -o bruteforce_knapsack.out
	g++ backtrack_knapsack.cpp -lm -o backtrack_knapsack.out
	
clean:
	rm -rf bruteforce_knapsack.out backtrack_knapsack.out